USE PEDIDOS; 

--SELECT * FROM TB_PRODUTO;
-- ITEM 01

SELECT TOP 15
	DESCRICAO AS NOME_PRODUTO,
	CAST(ROUND(PRECO_CUSTO * QTD_REAL ,2) AS DECIMAL (10,2)) AS VALOR_EM_ESTOQUE,
	CAST(ROUND(((PRECO_VENDA - PRECO_CUSTO)*QTD_REAL),2) AS DECIMAL (10,2)) AS LUCRO_BRUTO 
FROM TB_PRODUTO
ORDER BY VALOR_EM_ESTOQUE  DESC;

---------------------------------------------------------------------------------------------

--SELECT * FROM TB_PEDIDO;
-- ITEM 02

SELECT
	NUM_PEDIDO,
	SITUACAO,
	OBSERVACOES,
	DATA_EMISSAO 
FROM TB_PEDIDO
WHERE DATA_EMISSAO = '2013-01-01';
--- OBS: Exitem alguns campos com problemas no data type da data ex: '2013-01-05' funciona, mas se colocar '2013-01-02 não funciona.

SELECT
	NUM_PEDIDO,
	SITUACAO,
	OBSERVACOES,
	DATA_EMISSAO 
FROM TB_PEDIDO
WHERE (DATA_EMISSAO between 2013/01/01 AND 2013/02/28 OR DATA_EMISSAO between'2014-11-01' AND '2014-12-31' ) AND SITUACAO ='E' AND OBSERVACOES IS NOT NULL; 
ORDER BY DATA_EMISSAO;

---------------------------------------------------------------------------------------------

--SELECT * FROM TB_VENDEDOR;
-- ITEM 03

SELECT
	NOME,
	LOWER (REPLACE (NOME, ' ', '_')) + '@IMPACTA.COM.BR' AS EMAIL_VENDEDOR,
	CASE DATA_CAD
		WHEN NULL THEN 'NÃO POSSUI'
		ELSE 'POSSUI'
	END POSSUI_DATA
FROM TB_VENDEDOR
ORDER BY NOME;

---------------------------------------------------------------------------------------------

SELECT * FROM TB_EMPREGADO WHERE DATA_NASCIMENTO = '1980-5-5' ;
-- ITEM 04	

SELECT
	NOME,
	FLOOR(DATEDIFF( DAY,DATA_NASCIMENTO, GETDATE() )/365.25) AS IDADE_EMPREGADO,
	DATEPART(DAY, DATA_NASCIMENTO) AS DIA_NASCIMENTO,
	DATEPART( MONTH, DATA_NASCIMENTO) AS MES_NASCIMENTO,
	DATEPART( YEAR, DATA_NASCIMENTO) AS ANO_NASCIMENTO
FROM TB_EMPREGADO
WHERE DATEPART(WEEKDAY, DATA_NASCIMENTO) = 3 AND DATEPART( YEAR, DATA_NASCIMENTO) = 1980
ORDER BY NOME;

---------------------------------------------------------------------------------------------