CREATE TABLE TB_SUBCATEGORIA
(
ID_SUBCATEGORIA TINYINT PRIMARY KEY IDENTITY,
NM_SUBCATEGORIA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TB_IDIOMA
(
ID_IDIOMA TINYINT PRIMARY KEY,
NM_IDIOMA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TB_LIVRO
(
ISBN INT PRIMARY KEY,
NM_TITULO VARCHAR(100),
NM_AUTOR VARCHAR(100),
VL_LIVRO DECIMAL (10,2),
QT_PAGINAS SMALLINT,
PESO_GRAMAS SMALLINT,
NM_EDITORA VARCHAR(50),
NM_CATEGORIA VARCHAR(50),
ID_SUBCATEGORIA TINYINT,
ID_IDIOMA TINYINT,
CONSTRAINT FK_LIVRO_SUBCATEGORIA FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES TB_SUBCATEGORIA(ID_SUBCATEGORIA),
CONSTRAINT FK_LIVRO_IDIOMA FOREIGN KEY (ID_IDIOMA) REFERENCES TB_IDIOMA(ID_IDIOMA)
);